### ISSUE TITLE
Create Brimcap release artifacts

### ISSUE THREAD

**Issue by mattnibs** [brimdata/brimcap#11]
A brimcap release artifact should be created and include these dependencies:

1. The [suricata runner](https://github.com/brimdata/build-suricata)
2. The [zeek runner](https://github.com/brimdata/zeek)

The brimcap default config for analyzer should assume the zeekrunner and suricatarunner are adjacent to the brimcap executable path.

**Comment by philrz** [comment]
@mattnibs: I'm sure you'll bump into this, but keep in mind the role of the "suricata updater" as well.
