### ISSUE TITLE
Bring more config options into YAML (such as the Brimcap root)

### ISSUE THREAD

**Issue by philrz** [brimdata/brimcap#135]
A community user had been working off the Brim wiki [Remote Workspaces (v0.25.0+)](https://github.com/brimdata/brim/wiki/Remote-Workspaces-%28v0.25.0-%29) article, employing the technique of using Brimcap to locally index the pcaps that corresponded to logs that had been loaded into a remote Workspace, since this makes the **Packets** button work in the app. They then asked this question in a [message in a public Slack thread](https://brimsec.slack.com/archives/C010DR0HHMF/p1630112512015900?thread_ts=1630084715.014300&cid=C010DR0HHMF) (edited slightly for clarity):

> Is it possible to configure the "brimcap-root" path for brimcap when it is being used by the Brim app. If this was possible I presume it wouldn't be necessary for me to index the pcaps twice, since the brimcap-root directory on the zed server side is being shared over NFS and would be accessible to my local brim workstation...

There's a couple ways I can see that we could go about this. Since this represents a configurable setting, one approach that came to mind is Brimcap's Config YAML, since the Brim app already has the ability to point to a custom YAML config via a setting in **Preferences** (see the Brimcap wiki article for [Custom Brimcap Config](https://github.com/brimdata/brimcap/wiki/Custom-Brimcap-Config)). However, at the moment, only `brimcap analyze` uses the config YAML for things like pointing to analyzers, shaper configs, etc. In discussing this with @mattnibs, he agreed that we could expand the YAML to cover the other config options used by other commands such as what's currently only specified via `-root` for  `index` and `search`.

While discussing this, @mattnibs had a couple additional thoughts of what we could cover at the same time, and these sound like fine ideas to me also.

1.  We could have an environment variable that points to your config location
2.  I'd also like a `config` command that prints out the current config. This would be helpful just to see what the default config looks like.

**Comment by pasdesignal** [comment]
I will follow this issue with keen interest!

**Comment by philrz** [comment]
I've verified this functionality is working in Brimcap release tagged `v1.0.4`, though the Brim app is not able to fully make use of it yet. See https://github.com/brimdata/brim/issues/1821.

Using this YAML config based on what's shown in the [Custom Brimcap Config](https://github.com/brimdata/brimcap/wiki/Custom-Brimcap-Config) wiki article:

```
$ cat zeek-suricata.yml
root: /home/phil/other-root
analyzers:
  - cmd: /usr/local/bin/zeek-wrapper.sh
    name: zeek
  - cmd: /usr/local/bin/suricata-wrapper.sh
    name: suricata
    globs: ["eve.json"]
    shaper: |
      type port=uint16;
      type alert = {
        timestamp: time,
        event_type: bstring,
        src_ip: ip,
        src_port: port,
        dest_ip: ip,
        dest_port: port,
        vlan: [uint16],
        proto: bstring,
        app_proto: bstring,
        alert: {
          severity: uint16,
          signature: bstring,
          category: bstring,
          action: bstring,
          signature_id: uint64,
          gid: uint64,
          rev: uint64,
          metadata: {
            signature_severity: [bstring],
            former_category: [bstring],
            attack_target: [bstring],
            deployment: [bstring],
            affected_product: [bstring],
            created_at: [bstring],
            performance_impact: [bstring],
            updated_at: [bstring],
            malware_family: [bstring],
            tag: [bstring]
          }
        },
        flow_id: uint64,
        pcap_cnt: uint64,
        tx_id: uint64,
        icmp_code: uint64,
        icmp_type: uint64,
        tunnel: {
          src_ip: ip,
          src_port: port,
          dest_ip: ip,
          dest_port: port,
          proto: bstring,
          depth: uint64
        },
        community_id: bstring
      }
      filter event_type=="alert" | put this := shape(alert) | rename ts := timestamp
```

Invoking it in the `index` phase, we see the setting is used, as the `root` directory is populated with the index entry.

```
$ brimcap index -config zeek-suricata.yml -r sample.pcap

$ ls -l /home/phil/other-root
total 416
-rw------- 1 phil phil 424864 Sep  8 18:57 idx-aG5tLflou0WVcgKcj8VWAd30gui9d3SitZcqUahrKO4.json
```

Likewise during the `search` phase:

```
$ brimcap search -config zeek-suricata.yml -dst.ip 10.10.1.2 -dst.port 20669 -duration 2us -proto tcp -src.ip 10.192.135.181 -src.port 55811 -ts 2018-03-23T20:00:14.328598Z -w /tmp/mypcap.pcap

$ ls -l /tmp/mypcap.pcap 
-rw-rw-r-- 1 phil phil 176 Sep  8 19:00 /tmp/mypcap.pcap

$ tcpdump -r /tmp/mypcap.pcap 
reading from file /tmp/mypcap.pcap, link-type EN10MB (Ethernet)
13:00:14.328598 IP 10.192.135.181.55811 > 10.10.1.2.20669: Flags [S], seq 4093578379, win 1024, length 0
13:00:14.328600 IP 10.192.135.181.55811 > 10.10.1.2.20669: Flags [S], seq 4093578379, win 1024, length 0
```

That extracted flow isn't much to look at, but it shows it worked. 😉 

Keep an eye on https://github.com/brimdata/brim/issues/1821 for app-side updates.

Thanks @mattnibs!
