### ISSUE TITLE
Warn/prevent a user from loading the same pcap to the same Pool multiple times

### ISSUE THREAD

**Issue by philrz** [brimdata/brimcap#45]
As of GA Brimcap tagged `v0.0.2`, it's possible to `brimcap load` the same pcap multiple times to the same Space. Example:

```
$ zapi new -k archivestore wrccdc
wrccdc: space created

$ brimcap load -s wrccdc -root ~/brimcap-root ~/wrccdc.pcap
100.0% 500.0MB/500.0MB records=550398 

$ brimcap load -s wrccdc -root ~/brimcap-root ~/wrccdc.pcap
100.0% 500.0MB/500.0MB records=670823 

$ brimcap load -s wrccdc -root ~/brimcap-root ~/wrccdc.pcap
100.0% 500.0MB/500.0MB records=451812
```

At the end of this, there's only one pcap index in the Brimcap root, which seems reasonable.

```
~/brimcap-root$ ls -l
total 832
-rw-------  1 phil  staff  424848 Apr 20 08:35 idx-aG5tLflou0WVcgKcj8VWAd30gui9d3SitZcqUahrKO4.json

~/brimcap-root$ cat idx-aG5tLflou0WVcgKcj8VWAd30gui9d3SitZcqUahrKO4.json
...,"pcap_path":"/Users/phil/wrccdc.pcap"}
```

However, there's duplicate events in Brim. This is unsurprising because lakes do not attempt to deduplicate, but it would make it messy to work with the logs.

![](https://user-images.githubusercontent.com/5934157/115424926-febdc680-a1b3-11eb-9cdf-8ffed61acee7.png)

It seems like repeat loading of the same pcap to the same Space would almost always be a mistake, so the user would probably appreciate it if we were able to warn/prevent this, such as by pausing and confirming it's what they truly want to do. Perhaps we could offer some kind of `-force` option if the user truly wants to do it no matter what.

**Comment by philrz** [comment]
@mccanne correctly noted that upcoming Zed lake changes will make it easy for the user to unwind a mistaken extra `brimcap load` like this. However, since we have the info to warn the user before the redundant load even starts, we also agreed that would still be helpful to catch.

**Comment by nwt** [comment]
We removed `brimcap load` in #117.
