### ISSUE TITLE
pcap_path should be made absolute

### ISSUE THREAD

**Issue by philrz** [brimdata/brimcap#59]
Repro is with Brimcap commit `f9d1309`.

While doing some early work with Brimcap and the Brim app, I noticed that if I provide a non-absolute path to the pcap file I want to load, that's what ends up as the `pcap_path` in the index file. Example:

```
$ brimcap load -root ~/brimcap-root -s foo hello.pcapng 
100.0% 12.40KB/12.40KB records=12 

$ cat ~/brimcap-root/idx-Qw9A8BEMqN87ZMI8R2hnlYKwfCrBBYupSIr9URJGvJM.json | jq .
...
  ],
  "pcap_path": "hello.pcapng"
}
```

That effectively make it impossible for the pcap file to be found again, such as when the app invokes a `brimcap search`.

I know this problem is unlikely to happen in the "happy path" since I expect the app will always provide absolute paths in its assembled `brimcap load` command lines. However, we've already had interest from community users in running `brimcap load` directly at the CLI as part of automated workflows, so we should probably make sure we turn these into absolute paths before committing them to the file.

**Comment by mattnibs** [comment]
It definitely should and I thought did this. Will do 👍🏻

**Comment by philrz** [comment]
Verified using Brim commit `6078840` which talks to Zed commit `aa4170e`, along with Brimcap commit `a011e28` that includes this fix.

The way things fit together has changed a bit since this issue was opened, but here's the confirmation that the fix is working as intended, using the parts from my Dev installs at the above combo of commits.

```
$ brimcap -version
Version: v0.0.2-23-ga011e28

$ brimcap load -root $HOME/work/brim/run/data/brimcap-root -p foo hello.pcapng 
100.0% 12.40KB/12.40KB records=12 

$ cat $HOME/work/brim/run/data/brimcap-root/idx-Qw9A8BEMqN87ZMI8R2hnlYKwfCrBBYupSIr9URJGvJM.json | jq .
...
  ],
  "pcap_path": "/Users/phil/pcap/hello.pcapng"
}
```

Thanks @mattnibs!
