### ISSUE TITLE
Excessively detailed units shown during analysis

### ISSUE THREAD

**Issue by philrz** [brimdata/brimcap#95]
This is basically just a cosmetic thing and hence not urgent, but I noticed it in passing and figured I'd file. Repro is with Brimcap tagged `v0.0.4`.

During `brimcap analyze`, the "bytes" units shown in the progress meter appear to separately break out the mega/kilo/bytes portions. Since they're all smashed together, to me it becomes kind of impossible to parse visually and just becomes eye candy while I watch the percent-based meter. An improvement on this might be to show the units at one scale relative to the size of the pcap, i.e. if the pcap is \<1 GiB, show just MiB units.

```
$ brimcap analyze -o out.zng wrccdc.pcap 
100.0% 476MiB858KiB604B/476MiB858KiB604B records=582079 
```

https://user-images.githubusercontent.com/5934157/121394852-9f07b000-c906-11eb-8671-79ea82736383.mp4

**Comment by mccanne** [comment]
This should probably use `units.Bytes.Abbrev()` from `zed/pkg/units`.

**Comment by philrz** [comment]
I noticed that this has been fixed and have verified that the units have been brief & improved since the merging of #116. Here's verification current tip of `main`, which is Brimcap commit 8ab5276.

https://user-images.githubusercontent.com/5934157/126002821-17d8b5d9-a97f-4fc5-a847-476a10a8e294.mp4

Thanks @mattnibs!
